myapp/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'main'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
    path('', views.IndexMain.as_view(), name='index'),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

myapp/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # 글 작성하기
    path("write/", views.Write.as_view(), name='write'),
    # 글 상세 조회
    path("detail/<int:pk>/", views.DetailView.as_view(), name='detail'),
    # 글 수정 페이지
    path("detail/<int:pk>/edit/", views.Update.as_view(), name = 'edit'),
    # 글 삭제
    path("detail/<int:pk>/delete/", views.Delete.as_view(), name='delete'),
    # 검색 기능
    path("search/" ,views.Search.as_view(), name='search'),
    # 댓글 작성
    path("detail/<int:pk>/comment/write", views.CommentWrite.as_view(), name='cm-write'),
    # 댓글 수정
    path("detail/<int:pk>/comment/edit/", views.CommentUpdate.as_view(), name='cm-edit'),
    # 댓글 삭제
    path("detail/<int:pk>/comment/delete/", views.CommentDelete.as_view(), name='cm-delete'),
]

myapp/blog/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Location(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    location = models.ForeignKey(Location, on_delete=models.SET_NULL, null=True)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like = models.ManyToManyField(User, related_name='likes', blank=True)
    like_count = models.PositiveIntegerField(default=0)
    photo = models.ImageField(upload_to = "images/",blank=True, null=True)
    hit = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title
    
    @property
    def update_counter(self):
        self.hit += 1
        self.save()
        return self.hit


class Comment(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

myapp/blog/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ['title', 'location', 'content', 'photo']


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.TextInput(attrs={'placeholder': '댓글을 입력해주세요.'})
        }

myapp/blog/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from .models import Location, Post, Comment
from .forms import PostForm, CommentForm


### Post
class Write(LoginRequiredMixin, View):
    
    def get(self, request):
        form = PostForm()
        locations = Location.objects.all()
        context = {
            "title": "PostWrite",
            "form": form,
            "locations": locations
        }
        return render(request, 'blog/post_form.html', context)
    
    def post(self, request):
        form = PostForm(request.POST, request.FILES)

        if form.is_valid():
            post = form.save(commit=False)
            post.writer = request.user
            post.save()
            return redirect('/')
        
        context = {
            "form": form
        }
        return render(request, 'blog/post_form.html', context)



class Update(View):

    def get(self, request, pk):
        post = Post.objects.get(pk=pk)
        form = PostForm(initial={'title': post.title, 'photo':post.photo,'content':post.content})
        locations = Location.objects.all()
        context = {
            "title": "PostEdit",
            "form": form,
            "locations": locations,
            "post": post
        }
        return render(request, 'blog/post_edit.html', context)
    
    def post(self, request, pk):
        post = Post.objects.get(pk=pk)
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post.title = form.cleaned_data['title']
            post.location = form.cleaned_data['location']
            post.content = form.cleaned_data['content']
            if form.cleaned_data['photo']:
                post.photo = form.cleaned_data['photo']
            # if 'clear_photo' in request.POST:
            #     post.photo.delete()
            # else: print('----------이미지 삭제 구현X---------')
            post.save()
            return redirect('blog:detail', pk=pk)
        context = {
            "title": "PostEdit",
            "form": form
        }
        return render(request, 'blog/post_edit.html', context)


class Delete(View):
    
    def post(self, request, pk):
        post = Post.objects.get(pk=pk)
        post.delete()
        return redirect('/')


class DetailView(View):

    def get(self, request, pk):
        post = Post.objects.get(pk=pk)
        comments = Comment.objects.filter(post=post)
        comment_form = CommentForm()
        context = {
            "title": "Post",
            "post": post,
            "comments": comments,
            "comment_form": comment_form
        }
        return render(request, 'blog/post_detail.html', context)


### Search
class Search(View):
    def get(self, request):
        query = request.GET.get('search')
        posts = []
        if query:
            posts = Post.objects.filter(
                Q(title__icontains=query) |
                Q(location__name__icontains=query) |
                Q(writer__email__icontains=query)
            )
        return render(request, 'blog/post_search.html', {'posts': posts})


### Comment
class CommentWrite(LoginRequiredMixin, View):

    def post(self, request, pk):
        form = CommentForm(request.POST)
        post = Post.objects.get(pk=pk)

        if form.is_valid():
            content = form.cleaned_data['content']
            writer = request.user
            comment = Comment.objects.create(post=post, content=content, writer=writer)
            return redirect('blog:detail', pk=post.pk)
        context = {
            "title": "CommentWrite",
            "post": post,
            "form": form
        }
        return render(request, 'blog/post_detail.html', context)
    

class CommentUpdate(View):

    def post(self, request, pk):
        comment = Comment.objects.get(pk=pk)
        form = CommentForm(request.POST, instance=comment)

        if form.is_valid():
            form.save()
            return redirect('blog:detail', pk=comment.post.pk)

        post = comment.post
        comments = Comment.objects.filter(post=post)
        context = {
            "title": "Post",
            "post": post,
            "comments": comments,
            "comment_form": form
        }
        return render(request, 'blog/post_detail.html', context)


class CommentDelete(View):

    def post(self, request, pk):
        comment = Comment.objects.get(pk=pk)
        post_id = comment.post.id
        comment.delete()
        return redirect('blog:detail', pk=post_id)


### Like
class LikeToggle(LoginRequiredMixin, View):
    def post(self, request, pk):
        pass

myapp/blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block content %}
    <!-- Post -->
    <div class="main">


        <h2 class="main-title">글 조회</h2>
    
    
        <div class="view">
          <div class="view-header">
            <h2>{{ post.title }}</h2>
            <div class="view-info">
              <p>작성자: {{ post.writer }}</p>|
              <p>작성일: {{ post.created_at }}</p>|
              <p>수정일: {{ post.updated_at }}</p>
              <p>조회수: {{ post.update_counter }}</p>
            </div>
          </div>
          <div class="view-content">
            {% if post.location %}
            <p>위치: {{ post.location.name }}</p>
            {% endif %}
            <br>
            <p>{{ post.content }}</p>
            {% if post.photo %}
            <img src="{{ post.photo.url }}" alt="사진">
            {% endif %}
          </div>
          <!-- Comment -->
          <!-- 댓글 작성 -->
          <h3>댓글</h3>
            <form action="{% url 'blog:cm-write' pk=post.pk %}" method="post">
                {% csrf_token %}
                {% if comment_form.errors %}
                    {% with form=comment_form %}
                        {% include 'blog/form_error.html' %}
                    {% endwith %}
                {% else %}
                    {{ comment_form.content }}
                {% endif %}
                <input class="btn" type="submit" value="댓글 작성">
            </form>
            <br>
            <!-- 댓글 목록 -->
            {% if comments %}
            <ul>
                {% for comment in comments %}
                    <li>
                        {{ comment.content }} / {{ comment.created_at }} / {{ comment.writer }}
                        {% if comment.writer == request.user %}
                            <!-- 댓글 수정 버튼 -->
                            <div class="btn-group-comment">
                              <form action="{% url 'blog:cm-edit' pk=comment.pk %}" method="post">
                                {% csrf_token %}
                                {{ comment_form.as_p }}
                                <input class="btn" type="submit" value="댓글수정">
                              </form>
                              <!-- 댓글 삭제 버튼 -->
                              <form class="btn" action="{% url 'blog:cm-delete' pk=comment.pk %}" method="post">
                                  {% csrf_token %}
                                  <input type="submit" value="댓글삭제" class="btn">
                              </form>
                            </div>
                            
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
            {% else %}
            <p>댓글이 없습니다.</p>
            {% endif %}
        </div>
        <div class="btn-group">
          <a href="{% url 'index' %}" class="btn">목록</a>
          {% if post.writer == request.user %}
            <a href="{% url 'blog:edit' pk=post.pk %}" class="btn">수정</a>
            <form class="btn" action="{% url 'blog:delete' pk=post.pk %}" method="post">
              {% csrf_token %}
              <input type="submit" value="삭제" class="btn">
            </form>
          {% endif %}
        </div>
    
      </div>
    <!-- /Post -->

    <!-- Comment -->
{% endblock %}

myapp/blog/templates/blog/post_edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="main">
    <h2 class="main-title">글 수정하기</h2>
    <div class="view-header">
        <p>수정할 내용을 입력 해주세요.</p>
    </div>
    
    <div class="view">
        <form action="{% url 'blog:edit' pk=post.pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <table class="table write">
                <colgroup>
                <col style="width: 120px">
                <col>
                </colgroup>
                <tbody>
                <tr>
                    <th><label for="id_title">제목</label></th>
                    <td><input type="text" name="title" value="{{ post.title }}" required id="id_title" ></td>
                </tr>
                <tr>
                    <th><label for="location">위치</label></th>
                    <td>
                    <select name="location" id="id_location" >
                        {% for location in locations %}
                            {% if location.id == post.location.id %}
                                <option value="{{ location.id }}" selected>{{ location.name }}</option>
                            {% else %}
                                <option value="{{ location.id }}">{{ location.name }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                    </td>
                </tr>
                <tr>
                    <th><label for="id_content">내용</label></th>
                    <td>
                    <textarea id="id_content" name="content" required>{{ post.content }}</textarea>
                    </td>
                </tr>
                <tr>
                    <th><label for="id_photo">첨부된 파일</label></th>
                    <td>
                    <a href="{{ post.photo.url }}">{{ post.photo }}</a>
                    <input type="checkbox" name="photo-clear" id="photo-clear_id">
                    <label for="photo-clear_id">취소</label>
                    </td>
                </tr>
                <tr>
                    <th><label for="board-file">변경 파일첨부</label></th>
                    <td>
                        <input type="file" name="photo" accept="image/*" id="id_photo">
                    </td>
                </tr>
                </tbody>
            </table>
            <div class="btn-group">
                <input class="btn" type="submit" value="수정">
            </div>
        </form>
    </div>
{% endblock %}

myapp/blog/templates/blog/post_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="main">
    <h2 class="main-title">글쓰기</h2>
    <div class="view-header">
        <p>내용을 입력 해주세요.</p>
    </div>
    
    <div class="view">
        <form action="{% url 'blog:write' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <table class="table write">
                <colgroup>
                <col style="width: 120px">
                <col>
                </colgroup>
                <tbody>
                <tr>
                    <th><label for="title">제목{{ post.title }}</label></th>
                    <td><input type="text" id="board-title" name="title"></td>
                </tr>
                <tr>
                    <th><label for="location">위치</label></th>
                    <td>
                    <select id="location" name="location">
                        {% for location in locations %}
                        <option value="{{ location.id }}">{{ location.name }}</option>
                        {% endfor %}
                    </select>
                    </td>
                </tr>
                <tr>
                    <th><label for="board-content">내용{{ post.content }}</label></th>
                    <td>
                    <textarea id="board-content" name="content"></textarea>
                    </td>
                </tr>
                <tr>
                    <th><label for="board-file">파일첨부{{ post.photo }}</label></th>
                    <td>
                    <input type="file" id="board-file" name= "photo">
                    </td>
                </tr>
                </tbody>
            </table>
            <div class="btn-group">
                <button type="reset" class="btn">초기화</button>
                <input type="submit" value="작성" class="btn">
                <a href="{% url 'index' %}" class="btn">목록</a>
            </div>
        </form>
    </div>
    
{% endblock %}

myapp/blog/templates/blog/post_search.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% if posts %}
    <table class="table list">
        <colgroup>
          <col style="width: 30px">
          <col style="width: 120px">
          <col style="width: 80px">
          <col style="width: 100px">
          <col style="width: 60px">
          <col style="width: 60px">
        </colgroup>
        <thead>
          <tr>
            <th>번호</th>
            <th>제목</th>
            <th>작성자</th>
            <th>작성일</th>
            <th>위치</th>
            <th>조회수</th>
          </tr>
        </thead>
        <tbody>
            {% for post in posts reversed%}
            <tr>
                <td>{{ forloop.revcounter }}</td>
                <td><a href="{% url 'blog:detail' pk=post.pk %}">{{ post.title }}</a></td>
                <td>{{ post.writer }}</td>
                <td>{{ post.created_at }}</td>
                <td>{{ post.location }}</td>
                <td>{{ post.hit }}</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td class="nodata" colspan="5">등록된 게시물이 없습니다.</td>
            </tr>
            {% endif %}
        </tbody>
      </table>
      <!-- 글 작성 -->
      <form action="{% url 'blog:write' %}" method="get">
        {% csrf_token %}
        <input type="submit" value="글작성" class="btn-write">
      </form>
      <!-- /글 작성 -->
{% endblock %}