myapp/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'main'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
    path('', views.IndexMain.as_view(), name='index'),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

myapp/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    # 회원가입
    path("register/", views.Registration.as_view(), name='register'),
    # 로그인
    path("login/", views.Login.as_view(), name='login'),
    # 로그아웃
    path("logout/", views.Logout.as_view(), name='logout'),
    # 프로필 보기
    path("profile/", views.ProfileView.as_view(), name="profile"),
    # 프로필 생성
    path("profile/write/", views.ProfileWrite.as_view(), name="pf-write"),
    # 프로필 수정
]

myapp/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils import timezone


class UserManager(BaseUserManager):
    
    def _create_user(self, email, password, is_staff, is_superuser, **extra_fields):
        if not email:
            raise ValueError('User must have an email')
        # now = timezone.now() # 현재시간 -> UTC
        now = timezone.localtime()
        email = self.normalize_email(email)
        user = self.model(
            email=email,
            is_staff=is_staff,
            is_active=True,
            is_superuser=is_superuser,
            last_login=now,
            date_joined=now,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    # create_user
    def create_user(self, email, password, **extra_fields):
        return self._create_user(email, password, False, False, **extra_fields)
    # create_superuser
    def create_superuser(self, email, password, **extra_fields):
        return self._create_user(email, password, True, True, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, max_length=255)
    name = models.CharField(max_length=50, null=True, blank=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    last_login = models.DateTimeField(null=True, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    
    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []
    
    objects = UserManager()


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    nickname = models.CharField(max_length=15, default='')
    photo = models.ImageField(upload_to = "images/",blank=True, null=True)
    blog_url = models.URLField(max_length=60, blank=True, null=True)

    def __str__(self):
        return f'{self.user.email} Profile'

myapp/user/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from .fomrs import RegisterForm, LoginForm, ProfileForm
from .models import Profile

User = get_user_model()

### Registration
class Registration(View):
    
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('/')
        
        form = RegisterForm()
        context = {
            "title": "Register",
            "form": form
        }
        return render(request, 'user/user_register.html', context)
    
    def post(self, request):
        form = RegisterForm(request.POST)

        if form.is_valid():
            user = form.save()
            return redirect('/')
        context = {
            "title": "Register",
            "form": form
        }
        return render(request, 'user/user_register.html', context)


### Login
class Login(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('/')
        
        form = LoginForm()
        context = {
            'form': form,
            'title': 'User'
        }
        return render(request, 'user/user_login.html', context)
        
    def post(self, request):
        if request.user.is_authenticated:
            return redirect('/')
        
        form = LoginForm(request, request.POST)
        if form.is_valid():
            email = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=email, password=password)
            
            if user:
                login(request, user)
                return redirect('/')
        
        context = {
            'form': form
        }
        
        return render(request, 'user/user_login.html', context)
        

### Logout
class Logout(View):

    def get(self, request):
        logout(request)
        return redirect('/')
        pass

### Profile
class ProfileView(LoginRequiredMixin, View):

    def get (self, request):
        profile = Profile.objects.get(user=request.user.pk)
        context = {
            "title": "Profile",
            "profile": profile
        }
        return render(request, 'user/user_profile.html', context)


class ProfileWrite(View):
    
    def get (self, request):
        form = ProfileForm()
        context = {
            "title":"ProfileWrite",
            "form":form
        }
        return render(request, 'user/post_profile_write.html', context)
    
    def post(self, request):
        form = ProfileForm(request.POST, request.FILES)

        if form.is_valid():
            profile = form.save()
            profile.save()
            return redirect('user:pf-write')
        
        context = {
            "form": form
        }
        return render(request, 'user/post_profile_write.html', context)

myapp/user/templates/user/post_profile_write.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="main">
    <h2 class="main-title">프로필 작성하기</h2>
    <div class="view-header">
        <p>프로필을 작성해주세요.</p>
    </div>
    <div class="view">
        <br>
        <form action="{% url 'user:pf-write' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <input class="btn" type="submit" value="프로필 생성">
        </form>
    </div>
    
</div>
{% endblock %}

myapp/user/templates/user/user_login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="main">
    <div class="container">
      <h2 class="title">로그인</h2>
      <p class="description">아이디와 비밀번호를 입력하고 로그인하세요</p>

      <form class="login" action="{% url 'user:login' %}" method="post">
        {% csrf_token %}
        <div>
          <label class="label-width" for="user-id">아이디{{ login.email }}</label>
          <input type="text" id="user-id" name="username" required>
        </div>
        <div>
          <label class="label-width" for="user-pw">비밀번호{{ login.password }}</label>
          <input type="password" id="user-pw" name="password" required>
        </div>
        <div>
          <input type="checkbox" id="save-id" name="saveId">
          <label for="save-id">아이디 저장</label>
        </div>
        <input class="submit-button"  type="submit" value="로그인">
      </form>
    </div>
  </div>
{% endblock %}

myapp/user/templates/user/user_profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% if posts %}
        <p>닉네임:{{ profile.nickname }}</p>
        {% if post.photo %}
            <img src="{{ profile.photo.url }}" alt="프로필 사진">
        {% endif %}
        <p>블로그 주소:{{ profile.blog_url }}</p>
        <!-- 추가로 수정 버튼 만들기 -->
    {% else %}
        <p>등록된 프로필이 없습니다. 프로필을 만들어보세요.</p>
        <!-- 프로필 생성 버튼 -->
        <a class="btn" href="{% url 'user:pf-write' %}">프로필 생성</a>
    {% endif %}
{% endblock %}

myapp/user/templates/user/user_register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
      <div class="main">
        <div class="container">
          <h2 class="title">회원가입</h2>
          <p class="description">
            원활한 서비스를 이용을 위해 회원가입을 해주세요
          </p>
    
          <form class="login" action="{% url 'user:register' %}" method="post">
            {% csrf_token %}
            <div>
              <label class="label-width" for="id_email">이메일</label>
              <input type="email" id="id_email" name="email" autofocus required>
            </div>
            <div>
              <label class="label-width" for="id_password1">비밀번호{{ login.password }}</label>
              <input type="password" name="password1" autocomplete="new-password" required id="id_password1">
            </div>
            <div>
              <label class="label-width" for="id_password2">비밀번호 확인{{ login.password }}</label>
              <input type="password" name="password2" autocomplete="new-password" required id="id_password1">
            </div>
            <input class="submit-button" type="submit" value="회원가입">
          </form>
        </div>
      </div>

{% endblock %}